- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '/usr/local/bin/'
  tags:
    - zsh
- name: Update zshrc plugins
  shell: sed -i 's/(git/(git zsh-autosuggestions' ~/.zshrc
  tags:
    - zsh
- name: Install zsh theme
  ansible.builtin.git:
    repo: 'https://github.com/prescottbreeden/.zsh'
    dest: '~/'
  tags:
    - zsh
- name: Copy theme to oh-my-zsh themes
  shell: cp ~/.zsh/pb1337.zsh-theme ~/.oh-my-zsh/themes/pb1337.zsh-theme
  tags:
    - zsh
- name: Update zshrc theme
  shell: sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="pb1337"'
  tags:
    - zsh

